API_ID: 
API_HASH: 
BOT_TOKEN: 


MONGO_URL: 
REDIS_URI:redis://RBCHfnxxp0igFsomsD7RHKif
REDIS_PORT:9001
REDIS_PASS:RBCHfnxxp0igFsomsD7RHKif

SESSION_API_ID: 
SESSION_API_HASH: 
SESSION_STRING: 

ADMINS: 
  - 1317173146

OWNER: 1317173146

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

