API_ID: 26621235
API_HASH: 973693d0ee75cbfc53951b8c3debd1fe
BOT_TOKEN: 6187134031:AAHund_QezU0jqEq3PxC7v9PQ3WLMAhGF4s


MONGO_URL: mongodb+srv://ccheker:2020pdev@metomailer.n6wie.mongodb.net/ikkabot?retryWrites=true&w=majority
REDIS_URI: redis-18939.c289.us-west-1-2.ec2.cloud.redislabs.com
REDIS_PORT: 18939
REDIS_PASS: tnjhH91vHI15xL65xJtwVqRCGgESgDhU

SESSION_API_ID: 26621235
SESSION_API_HASH: 973693d0ee75cbfc53951b8c3debd1fe
SESSION_STRING: 1BVtsOJEBu62jPMcmOelIr-eXYByCQAI9AHBiT_jav5zcrP7XgTHqJVwwuJMA-VZ4Dp8EISEbzrr3kV7RI7RccJxlLi-e1fyB8yxl_8NLpEMWUV22osEoTy__UeAxr8uEAdys10iKS18Lf427fCdkh2pM9stZyP35A9Gfh-gHAdV9B3l2D5v4ygVsVeNq2YKbiB2_N3of4S9-FG3qC3tahKpNp65_MZrX_ESSQtOW5TvATa7Rvy2TDL86nNx2zDe0JhLD7CcP77iDA4Dc42bmUdbD6GE3MwIOAjlTbVtpCMwueHR8ncRxUSi8R-7IY_FvPQ2juoqePA1B5oA_6-nyYjkFLokpogs=

ADMINS: 
  - 948010462

OWNER: 948010462

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: TakashiKovacechats 
# LOG_CHAT: 
LOG_CHAT: -1001931622277



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

