API_ID: 26621235
API_HASH: 973693d0ee75cbfc53951b8c3debd1fe
BOT_TOKEN: 6187134031:AAHund_QezU0jqEq3PxC7v9PQ3WLMAhGF4s


MONGO_URL: mongodb+srv://ccheker:2020pdev@metomailer.n6wie.mongodb.net/ikkabot?retryWrites=true&w=majority
REDIS_URI: redis://RBCHfnxxp0igFsomsD7RHKif
REDIS_PORT: 9001
REDIS_PASS: RBCHfnxxp0igFsomsD7RHKif

SESSION_API_ID: 26621235
SESSION_API_HASH: 973693d0ee75cbfc53951b8c3debd1fe
SESSION_STRING: 1BVtsOKYBu6KlJT37A3Uuwt3cmo0fLeHjMTjHdQk3NcW02N4MMPAJ_mpTSiyhkiOTXs_uvIl2g7M2dzeSdhUBxuJ4tC7E6LGKMrkXvjMAzx18IjAyIjezlWGoldHZOs2iiczXNzeISOuBt_OD7d82YhwOJ2JFK6A0xVapQzP98OCYfUYf_XPZRllXat716Tcj8il3jB9t1VZUea7x5O2IkgqnqXZ-P8_PIYEekYXAGfccr2gDhvlNdOBWlbn16nE9igylQZTbgUhX7AoFcr33OhUN3UDuT1Oh8RtYK_F51XILDJyOjwBHiamMIUq-9W86ZljX4gFMQbZY6HL1x0FBHMD8iiBC0rA=

ADMINS: 
  - 948010462

OWNER: 948010462

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: -1001931622277



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

